#!/usr/bin/env python3
"""Generate StartupSplashAnimation.swift from the Silo startup splash Lottie.

The splash is rendered natively (SwiftUI Canvas) because the Aether purity
rule forbids any AVPlayer in production source. The Lottie JSON is produced
by src/splash.py in the silo-branding repo; this script bakes its shapes and
keyframes into Swift so the app carries no runtime Lottie parser.

Usage: scripts/generate-splash-animation.py scripts/splash/startup_splash.json > \
       iosApp/iosApp/Components/StartupSplashAnimation.swift
"""
import json
import sys


def fmt(x):
    return f"{x:.3f}".rstrip("0").rstrip(".") or "0"


def keyframes(prop, dims):
    if prop.get("a", 0) == 0:
        k = prop["k"]
        vals = k if isinstance(k, list) else [k]
        return [(0, vals[:dims])]
    out = []
    for kf in prop["k"]:
        assert not kf.get("h"), "hold keyframes unsupported"
        i, o = kf.get("i"), kf.get("o")
        if i and o:
            assert i["x"] == [0.5] and i["y"] == [0.5] and o["x"] == [0.5] and o["y"] == [0.5], "only linear eases supported"
        out.append((kf["t"], kf["s"][:dims]))
    return out


def swift_keyframes(kfs, dims):
    parts = []
    for t, vals in kfs:
        parts.append(f"K({t}, {', '.join(fmt(v) for v in vals[:dims])})")
    return "[" + ", ".join(parts) + "]"


def swift_path(shape):
    v, i, o = shape["v"], shape["i"], shape["o"]
    segs = []
    n = len(v)
    for k in range(n if shape.get("c", True) else n - 1):
        a = v[k]
        b = v[(k + 1) % n]
        c1 = [a[0] + o[k][0], a[1] + o[k][1]]
        c2 = [b[0] + i[(k + 1) % n][0], b[1] + i[(k + 1) % n][1]]
        segs.append(f"S({fmt(c1[0])}, {fmt(c1[1])}, {fmt(c2[0])}, {fmt(c2[1])}, {fmt(b[0])}, {fmt(b[1])})")
    return f"P(start: ({fmt(v[0][0])}, {fmt(v[0][1])}), segments: [{', '.join(segs)}])"


def main(path):
    d = json.load(open(path))
    assert d["fr"] == 60
    lines = []
    w, h, op = d["w"], d["h"], d["op"]
    lines.append("// Generated by scripts/generate-splash-animation.py from the Silo")
    lines.append("// startup splash Lottie (silo-branding/src/splash.py). Do not edit by hand.")
    lines.append("import CoreGraphics")
    lines.append("")
    lines.append("/// Shape and keyframe data for the native startup splash. Coordinates are")
    lines.append(f"/// in the {w}x{h} composition space at 60 fps.")
    lines.append("enum StartupSplashAnimation {")
    lines.append(f"    static let compositionSize = CGSize(width: {w}, height: {h})")
    lines.append(f"    static let frameCount = {op}")
    lines.append("    static let framesPerSecond: Double = 60")
    lines.append("")
    lines.append("    struct K { let t: Double; let v: [Double]; init(_ t: Double, _ v: Double...) { self.t = t; self.v = v } }")
    lines.append("    struct S { let c1: CGPoint; let c2: CGPoint; let end: CGPoint")
    lines.append("        init(_ a: Double, _ b: Double, _ c: Double, _ d: Double, _ e: Double, _ f: Double) {")
    lines.append("            c1 = CGPoint(x: a, y: b); c2 = CGPoint(x: c, y: d); end = CGPoint(x: e, y: f) } }")
    lines.append("    struct P { let start: (Double, Double); let segments: [S] }")
    lines.append("    struct Layer {")
    lines.append("        let name: String")
    lines.append("        let inPoint: Double")
    lines.append("        let anchor: CGPoint")
    lines.append("        let position: [K]")
    lines.append("        let scale: [K]")
    lines.append("        let color: (r: Double, g: Double, b: Double)")
    lines.append("        let paths: [P]")
    lines.append("    }")
    lines.append("")
    lines.append("    /// Bottom-to-top paint order (Lottie renders the highest index first).")
    lines.append("    static let layers: [Layer] = [")
    for L in reversed(d["layers"]):
        if L["ty"] != 4:
            continue
        ks = L["ks"]
        anchor = ks["a"]["k"]
        color = None
        paths = []
        for grp in L["shapes"]:
            for it in grp["it"]:
                if it["ty"] == "sh":
                    assert it["ks"].get("a", 0) == 0, "animated paths unsupported"
                    paths.append(swift_path(it["ks"]["k"]))
                elif it["ty"] == "fl":
                    color = it["c"]["k"]
                    assert it.get("r", 1) == 2, "expected even-odd fill"
        lines.append("        Layer(")
        lines.append(f"            name: \"{L['nm']}\",")
        lines.append(f"            inPoint: {L['ip']},")
        lines.append(f"            anchor: CGPoint(x: {fmt(anchor[0])}, y: {fmt(anchor[1])}),")
        lines.append(f"            position: {swift_keyframes(keyframes(ks['p'], 2), 2)},")
        lines.append(f"            scale: {swift_keyframes(keyframes(ks['s'], 2), 2)},")
        lines.append(f"            color: ({fmt(color[0])}, {fmt(color[1])}, {fmt(color[2])}),")
        lines.append("            paths: [")
        for p in paths:
            lines.append(f"                {p},")
        lines.append("            ]")
        lines.append("        ),")
    lines.append("    ]")
    lines.append("}")
    print("\n".join(lines))


if __name__ == "__main__":
    main(sys.argv[1])
